name: Install Dependencies
description: >
  Prepares CI requirements, caches pip dependencies, and installs them.

inputs:
  python-version:
    description: "Python version to set up"
    required: true
    default: "3.11"
runs:
  using: "composite"
  steps:
    - name: Prepare CI requirements
      shell: bash
      run: |
        cp requirements.txt requirements-ci.txt
        sed -i '/\(types\-tqdm\|black\|isort\|gunicorn\|django\-heroku\|uwsgi\)/d' requirements-ci.txt
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
