#!/bin/sh

# List of files staged for commit
changing_files=`git diff --cached --name-status | awk '$1 != "D" { print $2 }'`
passing=true

# Autoformat (autopep8) and Pylint
if echo $"changing_files" | grep .py ; then
    # The \e[ characters set colors in terminal, but look weird on Windows
    echo '\e[1;33mAutoformatting...\e[1;0m'
    docker exec tcf_django autopep8 --in-place --jobs=0 --max-line-length=100 --aggressive --aggressive -r tcf_website tcf_core
    echo '\e[1;33mLinting...\e[1;0m'
    docker exec tcf_django pylint --jobs=0 -s no --load-plugins pylint_django --django-settings-module=tcf_core.settings tcf_website tcf_core || { echo '\e[1;31mERROR: Pylint failed\e[1;0m'; passing=false; } 
else
    echo '\e[1;33mNo Python files changed, skipping autoformat.'
    echo '\e[1;33mNo Python files changed, skipping Pylint.\e[1;0m'
fi

# ESLint
if echo $"changing_files" | grep .js ; then
    docker exec tcf_django node_modules/.bin/eslint --cache --fix -c .config/.eslintrc.yml tcf_website/static/ || { echo '\e[1;31mERROR: ESLint failed\e[1;0m'; passing=false; } 
else
    echo '\e[1;33mNo JavaScript files changed, skipping ESLint.\e[1;0m'
fi

# Django tests
if echo $"changing_files" | grep .py ; then
    echo '\e[1;33mRunning tests...\e[1;0m'
    docker exec tcf_django coverage run manage.py test --keepdb || { echo '\e[1;31mERROR: Django tests failed\e[1;0m'; passing=false; }
else
    echo '\e[1;33mNo Python files changed, skipping Django tests.\e[1;0m'
fi

# Only commits if none of the checks failed, otherwise exits without committing
if [ "$passing" = true ] ; then
    echo '\e[1;32mSuccess!\e[1;0m'
else
    echo '\e[1;31mOne or more checks failed. Please fix and try committing again.\e[1;0m'
    exit 1
fi
