# Generated by Django 3.0.5 on 2020-04-03 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('computing_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('website', models.URLField(blank=True)),
                ('departments', models.ManyToManyField(to='tcf_website.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('professor_rating', models.FloatField(choices=[(1, 1.0), (2, 2.0), (3, 3.0), (4, 4.0), (5, 5.0)])),
                ('difficulty', models.FloatField(choices=[(1, 1.0), (2, 2.0), (3, 3.0), (4, 4.0), (5, 5.0)])),
                ('recommendability', models.FloatField(choices=[(1, 1.0), (2, 2.0), (3, 3.0), (4, 4.0), (5, 5.0)])),
                ('hours_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2999)])),
                ('season', models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=6)),
                ('number', models.IntegerField(help_text="As defined in SIS/Lou's List")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('computing_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('graduation_year', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2999)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Review')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mnemonic', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sis_section_number', models.IntegerField(unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Course')),
                ('instructors', models.ManyToManyField(to='tcf_website.Instructor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Section'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_last_taught',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='subdepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Subdepartment'),
        ),
    ]
