# Generated by Django 4.0.2 on 2022-02-18 20:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "computing_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2999),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdepartment", models.CharField(max_length=255)),
                (
                    "number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                    ),
                ),
                ("title", models.CharField(default="", max_length=225)),
                ("average", models.FloatField(default=0.0)),
                ("a_plus", models.IntegerField(default=0)),
                ("a", models.IntegerField(default=0)),
                ("a_minus", models.IntegerField(default=0)),
                ("b_plus", models.IntegerField(default=0)),
                ("b", models.IntegerField(default=0)),
                ("b_minus", models.IntegerField(default=0)),
                ("c_plus", models.IntegerField(default=0)),
                ("c", models.IntegerField(default=0)),
                ("c_minus", models.IntegerField(default=0)),
                ("d_plus", models.IntegerField(default=0)),
                ("d", models.IntegerField(default=0)),
                ("d_minus", models.IntegerField(default=0)),
                ("f", models.IntegerField(default=0)),
                ("ot", models.IntegerField(default=0)),
                ("drop", models.IntegerField(default=0)),
                ("withdraw", models.IntegerField(default=0)),
                ("total_enrolled", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CourseInstructorGrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=225)),
                ("middle_name", models.CharField(max_length=225)),
                ("last_name", models.CharField(max_length=225)),
                ("email", models.CharField(max_length=225)),
                ("subdepartment", models.CharField(max_length=255)),
                (
                    "number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                    ),
                ),
                ("title", models.CharField(default="", max_length=225)),
                ("average", models.FloatField(default=0.0)),
                ("a_plus", models.IntegerField(default=0)),
                ("a", models.IntegerField(default=0)),
                ("a_minus", models.IntegerField(default=0)),
                ("b_plus", models.IntegerField(default=0)),
                ("b", models.IntegerField(default=0)),
                ("b_minus", models.IntegerField(default=0)),
                ("c_plus", models.IntegerField(default=0)),
                ("c", models.IntegerField(default=0)),
                ("c_minus", models.IntegerField(default=0)),
                ("d_plus", models.IntegerField(default=0)),
                ("d", models.IntegerField(default=0)),
                ("d_minus", models.IntegerField(default=0)),
                ("f", models.IntegerField(default=0)),
                ("ot", models.IntegerField(default=0)),
                ("drop", models.IntegerField(default=0)),
                ("withdraw", models.IntegerField(default=0)),
                ("total_enrolled", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "instructor_rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "recommendability",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "enjoyability",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(80),
                        ]
                    ),
                ),
                (
                    "amount_reading",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "amount_writing",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "amount_group",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "amount_homework",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sis_section_number", models.IntegerField()),
                ("topic", models.TextField(blank=True)),
                ("units", models.CharField(blank=True, max_length=10)),
                ("section_type", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2999),
                        ]
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("FALL", "Fall"),
                            ("JANUARY", "January"),
                            ("SPRING", "Spring"),
                            ("SUMMER", "Summer"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="As defined in SIS/Lou's List", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subdepartment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("mnemonic", models.CharField(max_length=255, unique=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.department",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["year", "season"], name="tcf_website_year_caa60c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["number"], name="tcf_website_number_f6373e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("season", "year"), name="unique semesters"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="instructors",
            field=models.ManyToManyField(to="tcf_website.Instructor"),
        ),
        migrations.AddField(
            model_name="section",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.semester",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.course",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.instructor",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.semester",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="departments",
            field=models.ManyToManyField(to="tcf_website.Department"),
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.school",
            ),
        ),
        migrations.AddField(
            model_name="courseinstructorgrade",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.course",
            ),
        ),
        migrations.AddField(
            model_name="courseinstructorgrade",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.instructor",
            ),
        ),
        migrations.AddField(
            model_name="coursegrade",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester_last_taught",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.semester",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subdepartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.subdepartment",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["review"], name="tcf_website_review__5435a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "review"),
                name="unique vote per user and review",
            ),
        ),
        migrations.AddIndex(
            model_name="subdepartment",
            index=models.Index(
                fields=["department"], name="tcf_website_departm_85d335_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subdepartment",
            constraint=models.UniqueConstraint(
                fields=("mnemonic", "department"),
                name="unique subdepartment mnemonics per department",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["semester", "course"],
                name="tcf_website_semeste_8d4c29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["course"], name="tcf_website_course__ea693c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("sis_section_number", "semester"),
                name="unique sections per semesters",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["course", "instructor"],
                name="tcf_website_course__84da62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created"],
                name="tcf_website_user_id_0f70cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["school"], name="tcf_website_school__d40b59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("name", "school"), name="unique departments per school"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subdepartment", "number"],
                name="tcf_website_subdepa_f296bc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("subdepartment", "number"),
                name="unique course subdepartment and number",
            ),
        ),
    ]
