# Generated by Django 3.0.5 on 2020-04-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sis_section_number',
            field=models.IntegerField(),
        ),
    ]
