# Generated by Django 4.0.2 on 2022-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_times",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
