# Generated by Django 4.0.2 on 2022-02-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='short_title',
        ),
    ]
