# Generated by Django 3.0.5 on 2020-04-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_auto_20200403_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='instructor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Instructor'),
            preserve_default=False,
        ),
    ]
