# Generated by Django 4.1.1 on 2022-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0002_section_section_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
