# Generated by Django 3.0.5 on 2020-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_auto_20200404_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='computing_id',
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
