# Generated by Django 4.1.3 on 2022-11-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0003_review_hidden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdepartment',
            new_name='Subject',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique course subdepartment and number',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique subdepartment mnemonics per department',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='tcf_website_subdepa_f296bc_idx',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subdepartment',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='coursegrade',
            old_name='subdepartment',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='courseinstructorgrade',
            old_name='subdepartment',
            new_name='subject',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='tcf_website_departm_bc045b_idx',
            old_name='tcf_website_departm_85d335_idx',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'number'], name='tcf_website_subject_c49d00_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='unique course subject and number'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('mnemonic', 'department'), name='unique subject mnemonics per department'),
        ),
    ]
