# Generated by Django 4.1.5 on 2023-01-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0003_review_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
