# Generated by Django 4.0.2 on 2022-02-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0003_remove_blogpost_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(default='t', max_length=255),
            preserve_default=False,
        ),
    ]
