# Generated by Django 4.0.4 on 2022-04-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0003_question_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="placeholder",
            field=models.CharField(
                default="Enter your response here", max_length=100
            ),
        ),
    ]
