# Generated by Django 3.0.5 on 2020-04-04 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0004_auto_20200404_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
