# Generated by Django 4.1.1 on 2023-02-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0004_instructor_hidden"),
        (
            "tcf_website",
            "0004_remove_coursegrade_d_remove_coursegrade_d_minus_and_more",
        ),
    ]

    operations = []
