# Generated by Django 4.1.3 on 2022-11-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0004_rename_subdepartment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
