# Generated by Django 3.0.5 on 2020-04-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0004_auto_20200404_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='course',
            name='units',
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='units',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
