# Generated by Django 4.1.6 on 2023-02-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0003_review_hidden"),
        ("tcf_website", "0004_alter_question_placeholder"),
    ]

    operations = []
