# Generated by Django 4.0.3 on 2022-04-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0002_section_section_times'),
        ('tcf_website', '0005_delete_blogpost'),
    ]

    operations = [
    ]
