# Generated by Django 4.1.6 on 2023-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0005_merge_20230205_1937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursegrade",
            name="average",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="courseinstructorgrade",
            name="average",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
