# Generated by Django 4.1.6 on 2023-02-07 04:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0005_merge_20230205_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='department',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique course subdepartment and number',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='tcf_website_subdepa_f296bc_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subdepartment',
        ),
        migrations.AddField(
            model_name='course',
            name='sis_id',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.subject'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'number'], name='tcf_website_subject_c49d00_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='unique course subject and number'),
        ),
        migrations.DeleteModel(
            name='Subdepartment',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.department'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='tcf_website_departm_bc045b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('mnemonic', 'department'), name='unique subject mnemonics per department'),
        ),
    ]
