# Generated by Django 3.0.5 on 2020-04-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0005_auto_20200404_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(help_text="As defined in SIS/Lou's List", unique=True),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='mnemonic',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subdepartment', 'number'), name='unique course'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'school'), name='unique departments per school'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'course', 'instructor'), name='unique review per author, course, and instructor'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('sis_section_number', 'semester'), name='unique sections per semesters'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('season', 'year'), name='unique semesters'),
        ),
        migrations.AddConstraint(
            model_name='subdepartment',
            constraint=models.UniqueConstraint(fields=('mnemonic', 'department'), name='unique subdepartments'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique vote per user and review'),
        ),
    ]
