# Generated by Django 4.1.7 on 2023-02-19 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0005_merge_20230205_1952"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="semester",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.semester",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="instructor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tcf_website.instructor",
            ),
        ),
        migrations.CreateModel(
            name="VoteQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.answer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="votequestion",
            index=models.Index(
                fields=["question"], name="tcf_website_questio_ea2a57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="votequestion",
            constraint=models.UniqueConstraint(
                fields=("user", "question"),
                name="unique vote per user and question",
            ),
        ),
        migrations.AddIndex(
            model_name="voteanswer",
            index=models.Index(
                fields=["answer"], name="tcf_website_answer__fc907a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voteanswer",
            constraint=models.UniqueConstraint(
                fields=("user", "answer"),
                name="unique vote per user and answer",
            ),
        ),
    ]
