# Generated by Django 4.1.2 on 2022-10-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0003_review_hidden'),
        ('tcf_website', '0006_merge_0002_section_section_times_0005_delete_blogpost'),
    ]

    operations = [
    ]
