# Generated by Django 3.0.5 on 2020-04-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0006_auto_20200404_1936'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique course',
        ),
        migrations.RemoveConstraint(
            model_name='subdepartment',
            name='unique subdepartments',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('subdepartment', 'number'), name='unique course subdepartment and number'),
        ),
        migrations.AddConstraint(
            model_name='subdepartment',
            constraint=models.UniqueConstraint(fields=('mnemonic', 'department'), name='unique subdepartment mnemonics per department'),
        ),
    ]
