# Generated by Django 4.1.8 on 2023-04-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0004_grades_data_overhaul"),
        (
            "tcf_website",
            "0006_answer_semester_question_instructor_votequestion_and_more",
        ),
    ]

    operations = []
