# Generated by Django 4.1.8 on 2023-04-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0007_merge_20230409_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(),
        ),
    ]
