# Generated by Django 3.0.5 on 2020-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0008_auto_20200404_1945'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review per author, course, and instructor',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'course'), name='unique review per author and course'),
        ),
    ]
