# Generated by Django 4.1.6 on 2023-02-09 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0008_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the post will be         published. If you want to schedule a post for the future, set this to a future date.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='The URL that the post will have. Match it to the headline, keep length at 3-5             words, and use dashes between words. Example: "what-is-url-slug"                 (More info: https://rockcontent.com/blog/what-is-url-slug/)', unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
