# Generated by Django 4.1.8 on 2023-04-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0008_alter_question_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="placeholder",
        ),
    ]
