# Generated by Django 4.2.8 on 2024-01-24 21:30

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0009_remove_question_placeholder'),
    ]

    operations = [
        TrigramExtension(),
    ]
