# Generated by Django 4.2.8 on 2024-04-17 18:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0010_trigram_extension"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="tcf_website_subdepa_f296bc_idx",
        ),
        migrations.AddField(
            model_name="course",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="tcf_website_search_880378_gin"
            ),
        ),
    ]
