# Generated by Django 4.2.8 on 2024-03-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0010_schedule_scheduledcourse"),
        ("tcf_website", "0010_trigram_extension"),
    ]

    operations = []
