# Generated by Django 3.0.5 on 2020-04-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0010_auto_20200405_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='professor_rating',
            new_name='instructor_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='section',
        ),
    ]
