# Generated by Django 4.2.8 on 2024-04-17 19:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tcf_website",
            "0011_remove_course_tcf_website_subdepa_f296bc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="instructor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="tcf_website_search_4770c8_gin"
            ),
        ),
    ]
