# Generated by Django 3.0.5 on 2020-04-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0011_auto_20200405_2207'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review per author and course',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'instructor'), name='unique review per user, course, and instructor'),
        ),
    ]
