# Generated by Django 4.2.13 on 2024-05-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0012_instructor_search_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="instructor",
            name="tcf_website_search_4770c8_gin",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="search",
        ),
    ]
