# Generated by Django 4.2.13 on 2024-07-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0011_merge_20240304_1700"),
        ("tcf_website", "0012_alter_review_email"),
    ]

    operations = []
