# Generated by Django 3.0.5 on 2020-04-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0012_auto_20200405_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.Semester'),
            preserve_default=False,
        ),
    ]
