# Generated by Django 3.0.5 on 2020-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0013_review_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='computing_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
