# Generated by Django 4.2.13 on 2024-10-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0013_discipline_section_cost_course_disciplines"),
        ("tcf_website", "0013_merge_20240730_1959"),
    ]

    operations = []
