# Generated by Django 4.2.16 on 2024-10-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0013_discipline_section_cost_course_disciplines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="website",
        ),
    ]
