# Generated by Django 4.2.13 on 2024-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0013_discipline_section_cost_course_disciplines"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="instructor",
            index=models.Index(
                fields=["first_name", "last_name"], name="tcf_website_first_n_59696b_idx"
            ),
        ),
    ]
