# Generated by Django 4.2.16 on 2024-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0013_discipline_section_cost_course_disciplines"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="enrollment_limit",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="enrollment_total",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_limit",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_total",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
