# Generated by Django 3.0.5 on 2020-04-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0014_auto_20200405_2249'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review per user, course, and instructor',
        ),
    ]
