# Generated by Django 4.2.16 on 2024-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0016_course_title_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="enrollment_limit",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="enrollment_total",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_limit",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_total",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
