# Generated by Django 3.0.5 on 2020-04-06 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0016_auto_20200405_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 58, 14, 597056, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 58, 14, 597092, tzinfo=utc)),
        ),
    ]
