# Generated by Django 4.2.13 on 2025-01-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0014_merge_20241020_1820"),
        ("tcf_website", "0016_course_title_gin_index"),
    ]

    operations = []
