# Generated by Django 4.2.18 on 2025-03-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0017_sectiontime"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="avg_difficulty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="avg_hours_per_week",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseInstructorMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("avg_difficulty", models.FloatField(blank=True, null=True)),
                ("avg_recommendability", models.FloatField(blank=True, null=True)),
                ("avg_enjoyability", models.FloatField(blank=True, null=True)),
                ("avg_instructor_rating", models.FloatField(blank=True, null=True)),
                ("avg_hours_per_week", models.FloatField(blank=True, null=True)),
                ("avg_amount_reading", models.FloatField(blank=True, null=True)),
                ("avg_amount_writing", models.FloatField(blank=True, null=True)),
                ("avg_amount_group", models.FloatField(blank=True, null=True)),
                ("avg_amount_homework", models.FloatField(blank=True, null=True)),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tcf_website.course"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tcf_website.instructor"
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "instructor")},
            },
        ),
    ]
