# Generated by Django 4.2.16 on 2024-11-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0017_sectiontime"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionEnrollment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enrollment_taken", models.IntegerField(blank=True, null=True)),
                ("enrollment_limit", models.IntegerField(blank=True, null=True)),
                ("waitlist_taken", models.IntegerField(blank=True, null=True)),
                ("waitlist_limit", models.IntegerField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tcf_website.section"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment_taken"], name="tcf_website_enrollm_a003a0_idx"
                    ),
                    models.Index(
                        fields=["enrollment_limit"], name="tcf_website_enrollm_a40cdb_idx"
                    ),
                    models.Index(fields=["waitlist_taken"], name="tcf_website_waitlis_5cf666_idx"),
                    models.Index(fields=["waitlist_limit"], name="tcf_website_waitlis_916c18_idx"),
                ],
            },
        ),
    ]
