# Generated by Django 4.2.16 on 2025-04-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0017_merge_20250102_1752"),
        ("tcf_website", "0018_courseenrollment_sectionenrollment"),
    ]

    operations = []
