# Generated by Django 4.2.18 on 2025-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0019_populate_review_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
