# Generated by Django 4.2.20 on 2025-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0019_merge_20250401_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="toxicity_category",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="toxicity_rating",
            field=models.IntegerField(default=0),
        ),
    ]
