# Generated by Django 5.2.6 on 2025-10-06 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0022_coursegrade_tcf_website_course__76e103_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
