# Generated by Django 4.2.19 on 2025-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0022_coursegrade_tcf_website_course__76e103_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True if instructor is not teaching in current semester'),
        ),
    ]
