# Generated by Django 4.2.26 on 2025-11-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0022_coursegrade_tcf_website_course__76e103_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionenrollment",
            name="section",
        ),
        migrations.AddField(
            model_name="section",
            name="enrollment_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="enrollment_taken",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="waitlist_taken",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CourseEnrollment",
        ),
        migrations.DeleteModel(
            name="SectionEnrollment",
        ),
    ]
