# Generated by Django 4.2.26 on 2025-12-06 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0023_remove_sectionenrollment_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLLMSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                ("model_id", models.CharField(default="openrouter/auto", max_length=255)),
                ("source_review_count", models.PositiveIntegerField(default=0)),
                ("last_review_id", models.IntegerField(default=0)),
                ("source_metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.instructor",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.club",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=django.db.models.expressions.Q(("club__isnull", True)),
                        fields=("course", "instructor"),
                        name="unique_summary_per_course_instructor",
                    ),
                    models.UniqueConstraint(
                        condition=django.db.models.expressions.Q(("club__isnull", False)),
                        fields=("club",),
                        name="unique_summary_per_club",
                    ),
                ],
            },
        ),
    ]
