# Generated by Django 4.2.28 on 2026-02-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0023_remove_sectionenrollment_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
