# Generated by Django 4.2.27 on 2026-02-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0023_remove_sectionenrollment_section_and_more"),
        ("tcf_website", "0023_user_karma"),
    ]

    operations = []
