# Generated by Django 4.2.24 on 2025-10-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0023_reviewllmsummary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reviewllmsummary",
            new_name="tcf_website_course__a7afbf_idx",
            old_name="tcf_website_reviewllmsum_course_instr_idx",
        ),
        migrations.RenameIndex(
            model_name="reviewllmsummary",
            new_name="tcf_website_club_id_9c8d0c_idx",
            old_name="tcf_website_reviewllmsum_club_idx",
        ),
    ]
