# Generated by Django 4.2.28 on 2026-02-04 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0023_remove_sectionenrollment_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Forum Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tcf_website.forumcategory",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Associate this post with a specific course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tcf_website.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Associate this post with a specific instructor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tcf_website.instructor",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tcf_website.semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-created"],
            },
        ),
        migrations.CreateModel(
            name="ForumResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tcf_website.forumresponse",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.forumpost",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tcf_website.semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ForumPostVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.forumpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumResponseVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.forumresponse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["response"], name="tcf_website_respons_9e6520_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="forumresponsevote",
            constraint=models.UniqueConstraint(
                fields=("user", "response"), name="unique_forum_response_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="forumresponse",
            index=models.Index(
                fields=["post", "created"], name="tcf_website_post_id_fb68e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumresponse",
            index=models.Index(
                fields=["parent"], name="tcf_website_parent__dfe306_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumresponse",
            index=models.Index(fields=["user"], name="tcf_website_user_id_96c7b4_idx"),
        ),
        migrations.AddIndex(
            model_name="forumpostvote",
            index=models.Index(fields=["post"], name="tcf_website_post_id_6f9896_idx"),
        ),
        migrations.AddConstraint(
            model_name="forumpostvote",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_forum_post_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["-created"], name="tcf_website_created_8e8506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["course"], name="tcf_website_course__6ee5fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(fields=["user"], name="tcf_website_user_id_1d2555_idx"),
        ),
        migrations.AddIndex(
            model_name="forumpost",
            index=models.Index(
                fields=["category"], name="tcf_website_categor_fba48e_idx"
            ),
        ),
    ]
