# Generated by Django 4.2.26 on 2026-01-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0024_course_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="related_courses",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
