# Generated by Django 5.2.7 on 2025-12-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0024_studyguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyguide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
