# Generated by Django 4.2.27 on 2026-03-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0024_merge_20260201_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default="anonymous", max_length=150),
        ),
    ]
