# Generated by Django 4.2.29 on 2026-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0024_merge_20260201_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selected_pfp",
            field=models.CharField(blank=True, default="pfpteam1.png", max_length=50),
        ),
    ]
