# Generated by Django 4.2.25 on 2025-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0024_votereply_votereply_unique_vote_per_user_and_reply"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reply",
            constraint=models.UniqueConstraint(
                fields=("user", "review"), name="unique reply per user and review"
            ),
        ),
    ]
