# Generated by Django 4.2.29 on 2026-04-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0025_section_units_and_schedule_enrolled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLLMSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                ("model_id", models.CharField(max_length=255)),
                ("source_review_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.instructor",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reviewllmsummary",
            constraint=models.UniqueConstraint(
                fields=("course", "instructor"), name="unique_course_instructor_summary"
            ),
        ),
    ]
