# Generated by Django 4.2.27 on 2026-02-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0024_course_prerequisites"),
        ("tcf_website", "0025_course_related_courses"),
    ]

    operations = []
