# Generated by Django 4.2.27 on 2026-04-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0025_user_nickname"),
        ("tcf_website", "0025_user_selected_pfp"),
    ]

    operations = []
