# Generated by Django 4.2.28 on 2026-03-04 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0025_question_instructor_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="parent_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="tcf_website.answer",
            ),
        ),
    ]
