# Generated by Django 4.2.28 on 2026-03-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0026_answer_parent_answer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique answer per user and question",
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_answer__isnull", True)),
                fields=("user", "question"),
                name="unique answer per user and question",
            ),
        ),
    ]
