# Generated by Django 4.2.29 on 2026-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0026_reviewllmsummary_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "course"], name="tcf_website_user_id_1ac1e7_idx"
            ),
        ),
    ]
