# Generated by Django 4.2.29 on 2026-04-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0027_add_review_user_course_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="share_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ScheduleBookmark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewer_bookmarks",
                        to="tcf_website.schedule",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["viewer", "schedule"],
                        name="tcf_website_viewer__65eaf9_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedulebookmark",
            constraint=models.UniqueConstraint(
                fields=("viewer", "schedule"),
                name="tcf_schedulebookmark_viewer_schedule_uniq",
            ),
        ),
    ]
