# Generated by Django 5.2.8 on 2026-04-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0024_seed_browse_schools'),
        ('tcf_website', '0028_schedule_share_token_schedulebookmark_and_more'),
    ]

    operations = [
    ]
