# Generated by Django 4.2.30 on 2026-07-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0028_schedule_share_token_schedulebookmark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("average_instructor_rating", models.FloatField(blank=True, null=True)),
                ("average_difficulty", models.FloatField(blank=True, null=True)),
                ("average_recommendability", models.FloatField(blank=True, null=True)),
                ("average_enjoyability", models.FloatField(blank=True, null=True)),
                ("average_hours_per_week", models.FloatField(blank=True, null=True)),
                ("average_amount_reading", models.FloatField(blank=True, null=True)),
                ("average_amount_writing", models.FloatField(blank=True, null=True)),
                ("average_amount_group", models.FloatField(blank=True, null=True)),
                ("average_amount_homework", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="tcf_website.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseInstructorStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("average_instructor_rating", models.FloatField(blank=True, null=True)),
                ("average_difficulty", models.FloatField(blank=True, null=True)),
                ("average_recommendability", models.FloatField(blank=True, null=True)),
                ("average_enjoyability", models.FloatField(blank=True, null=True)),
                ("average_hours_per_week", models.FloatField(blank=True, null=True)),
                ("average_amount_reading", models.FloatField(blank=True, null=True)),
                ("average_amount_writing", models.FloatField(blank=True, null=True)),
                ("average_amount_group", models.FloatField(blank=True, null=True)),
                ("average_amount_homework", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_stats",
                        to="tcf_website.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_stats",
                        to="tcf_website.instructor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course", "instructor"],
                        name="tcf_website_course__ef5d6b_idx",
                    ),
                    models.Index(
                        fields=["instructor", "course"],
                        name="tcf_website_instruc_323249_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courseinstructorstats",
            constraint=models.UniqueConstraint(
                fields=("course", "instructor"), name="unique_course_instructor_stats"
            ),
        ),
    ]
