# Generated by Django 4.2.28 on 2026-05-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0029_alter_answer_semester"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique answer per user and question",
        ),
    ]
