# Generated by Django 4.2.30 on 2026-10-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0029_school_of_data_science'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructorSemesterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0.0, null=True)),
                ('a_plus', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('a_minus', models.IntegerField(default=0)),
                ('b_plus', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('b_minus', models.IntegerField(default=0)),
                ('c_plus', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('c_minus', models.IntegerField(default=0)),
                ('dfw', models.IntegerField(default=0)),
                ('total_enrolled', models.IntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.instructor')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcf_website.semester')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'instructor', 'semester'], name='tcf_website_course__5ae076_idx')],
            },
        ),
    ]
