# Generated by Django 4.2.30 on 2026-09-21 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf_website', '0030_review_optional_hours_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRateDismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf_website.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='quickratedismissal',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'instructor'), name='unique_quick_rate_dismissal'),
        ),
    ]
