"""TCF Models module."""

# See
# https://docs.djangoproject.com/en/3.0/topics/db/models/#organizing-models-in-a-package

from .models import (
    CATALOG_YEAR_WINDOW,
    REVIEW_STAT_FIELDS,
    Answer,
    Club,
    ClubCategory,
    Course,
    CourseGrade,
    CourseInstructorGrade,
    CourseInstructorStats,
    CourseStats,
    Department,
    Discipline,
    Instructor,
    Question,
    Review,
    ReviewLLMSummary,
    Schedule,
    ScheduleBookmark,
    ScheduledCourse,
    School,
    Section,
    SectionTime,
    Semester,
    Subdepartment,
    User,
    Vote,
)
from .stats import (
    recompute_all_stats,
    recompute_course_instructor_stats,
    recompute_course_stats,
    recompute_stats_for_review_target,
)

__all__ = [
    "CATALOG_YEAR_WINDOW",
    "REVIEW_STAT_FIELDS",
    "Answer",
    "Club",
    "ClubCategory",
    "Course",
    "CourseGrade",
    "CourseInstructorGrade",
    "CourseInstructorStats",
    "CourseStats",
    "Department",
    "Discipline",
    "Instructor",
    "Question",
    "Review",
    "ReviewLLMSummary",
    "Schedule",
    "ScheduleBookmark",
    "ScheduledCourse",
    "School",
    "Section",
    "SectionTime",
    "Semester",
    "Subdepartment",
    "User",
    "Vote",
    "recompute_all_stats",
    "recompute_course_instructor_stats",
    "recompute_course_stats",
    "recompute_stats_for_review_target",
]
