env:
  browser: true
  es2021: true
  jquery: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  getCookie: readonly
rules:
  {
    "indent": ["error", 4],
    "quotes": ["error", "double", { "avoidEscape": true }],
    "no-inline-comments": "off",
    "semi": ["error", "always"],
    "space-before-function-paren": ["error", "never"]
  }
